# Generated by Django 4.1.6 on 2023-02-15 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=500, null=True)),
                ('thumbnail', models.CharField(max_length=100, null=True)),
                ('image', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=400)),
                ('uid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gnovelapi.comic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gnovelapi.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='comics',
            field=models.ManyToManyField(through='gnovelapi.User_Comic', to='gnovelapi.comic'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('text', models.CharField(max_length=500)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gnovelapi.comic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gnovelapi.user')),
            ],
        ),
    ]
