# Generated by Django 4.1.6 on 2023-02-25 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnovelapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_comic',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_comics', to='gnovelapi.comic'),
        ),
    ]
