# Generated by Django 4.1.6 on 2023-02-25 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnovelapi', '0002_alter_user_comic_comic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='image',
        ),
    ]
